Fix AsyncRestClient Missing SSL Params
Configuration arguments aren't correctly passed into the async rest client. This can result in ssl errors even after we've disabled ssl verification in the configuration.

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)